### ISSUE TITLE
Loop in provisioning objects

### ISSUE THREAD

**Issue by Asgoret** [openshift/ansible-service-broker#1145]
Hi! 
**What happened**:
I start provisioning (via GUI)(for example) Service and task end successfully, but deprovision process start at same time. I can't find any errors in pod. It looks like: provision-succes-deprovision-success-provision... and doesn't end
**What you expected to happen**:
Complete provision process.

Information:
Service yaml:
```
apiVersion: v1
kind: Service
metadata:
  name: {{ app }}
  namespace: {{ namespace }}
  labels:
    app: {{ app }}
    app-group: {{ app_group }}
  name: {{ app }}-{{ service_postfix }}
spec:
  selector:
    deploymentconfig: {{ app }}
  sessionAffinity: None
  type: {{ 'ClusterIP' if service_type|default(ClusterIP) else 'NodePort' }}
  ports:
    - protocol: {{ protocol }}
      port: {{ port }}
      targetPort: {{ route_port }}
      name: {{ port }}-{{ protocol|lower }}
```

Taks in main.yml
```
- name: Set simple object state="{{ state }}"
  k8s:
    force: yes
    state: "{{ state }}"
    definition: "{{ lookup ('template', item.name)}}"
  when: item.apply|default(false)
  loop:
    - name: service.yaml.j2
      apply: "{{ deploy_service|default('',true) }}"
```

Also i saw this `Provision call failed: Error occurred during provision. Please contact administrator if the issue persists.` but i can't understand where is issue if service created successfully and if i create it from CLI all works fine.
