### ISSUE TITLE
Helm registry adapter HTTP basic authentication

### ISSUE THREAD

**Issue by RikuXan** [openshift/ansible-service-broker#1183]
Is it possible to use HTTP basic authentication with the Helm registry adapter? 

The only reference to HTTP basic auth that I can see in the docs refer to the broker's authentication itself, for the registries I can only find the `user` and `pass` configuration variables which seem to be specific to certain registry types (e.g. Docker Hub or RHCC) and are not translated into HTTP basic auth headers.  
Embedding the credentials in the URL does not seem to work either.

**Comment by jmrodri** [comment]
Looking at the code, the `helm_adapter` definitely doesn't use the `user`, `password` or `auth_type` that is supported in the registry `Configuration`. That being said the user and pass in the url should work.
```
registry:
  - name: stable
    type: helm
    url: "https://user:pass@kubernetes-charts.storage.googleapis.com"
    runner: "docker.io/automationbroker/helm-runner:latest"
    white_list:
      - ".*"
```
Seems like the above syntax should work. We don't do anything with the URL, we simply pass it along without transformation. What does your configuration look like? (please sanitize any sensitive values before posting configs).
