### ISSUE TITLE
Non-quoted numeric bind credentials cause other bind credentials to disappear from secrets.

### ISSUE THREAD

**Issue by djwhatle** [openshift/ansible-service-broker#335]
> ### Bug: Non-quoted numeric bind credentials cause other bind credentials to disappear from secrets.

**What happened**:

1. Ran a MySQL APB containing an `asb_encode_binding` command including a port number.
```
- name: Encode bind credentials
  asb_encode_binding:
    fields:
      DB_TYPE: "mysql"
      DB_PASSWORD: "{{ MasterUserPassword }}"
      DB_NAME: "{{ DBName }}"
      DB_HOST: "{{ rds_endpoint_address }}"
      DB_PORT: "{{ PortNumber }}"
      DB_USER: "{{ MasterUsername }}"
```
 2. Created a hello-world APB to bind to the database 
 3. Binded the hello-world APB to database
 4. Inspected the secret created as a result of bind
 5. Noticed that secret created only contained the first 3/6 encoded fields

 6. Added escaped quotes around port number encode line
```
      DB_PORT: "\"{{ PortNumber }}\""
```
 7. Re-deployed MySQL APB, hello-world APB
 8. All bind credentials showed up as expected

 
**What you expected to happen**:
Same as above but expected all fields to show up in secret without needing to put quotes around DB_PORT value. Alternatively, would have been useful to receive an error message explaining the issue and workaround.
