### ISSUE TITLE
Whitelist item must contain org to filter image ?

### ISSUE THREAD

**Issue by mdshuai** [openshift/ansible-service-broker#379]
**What happened**:
In whitelist I must contain org, not sure if this is by design. But in the [doc example](https://github.com/openshift/ansible-service-broker/blob/master/docs/filtering_apbs.md#example-config-file). I don't see it
1. Configure whitelist like below, `mediawiki123-apb` doesn't math whitelist, I must use `^ansibleplaybookbundle/mediawiki123-apb$`

```
    registry:
      -
        name: apb
        org: ansibleplaybookbundle
        pass: ""
        type: dockerhub
        url: "https://registry.hub.docker.com"
        fail_on_error: true
        user: ""
        white_list:
          - "hello.*-apb$"
          - "^mediawiki123-apb$"
```
