### ISSUE TITLE
Missing type field on parameter causes empty catalog request

### ISSUE THREAD

**Issue by cfchase** [openshift/ansible-service-broker#388]
**This form is for bug reports and feature requests. Major features will go through a [spec process](https://github.com/openshift/ansible-service-broker/blob/master/CONTRIBUTING.md).**

# Bug:
Omitting type from a parameter causes an empty response when requesting the catalog.  

**What happened**:
After uploading an APB with an error in it (in this case missing the type field was missing on a parameter), requests to the broker catalog came back empty.

**What you expected to happen**:
* Defaults the type for the parameter to something (string?)
* I would expect for a bad APB to be missing from the response, but I would expect the other APBs to be returned when requesting the catalog.  Seems like bad APBs might get uploaded so we should handle that more gracefully.

**How to reproduce it**:
1. Create an APB with a single parameter with only the name field.
```yaml
name: hello-world-apb
plans:
  - name: default
    parameters:
      - name: test_param_string
#       type: string # commented out will result in empty catalog
```
2. Build, push the apb.
```
apb build
...
docker push ...
```
3. Boostrap the broker
```
apb bootstrap # or curl -X POST http://0.0.0.0:1338/v2/bootstrap
```
4. GET request the catatalog
```
apb list -o json # or curl -X GET http://0.0.0.0:1338/v2/catalog
```
