### ISSUE TITLE
Improve registry config

### ISSUE THREAD

**Issue by eriknelson** [openshift/ansible-service-broker#49]
Registries are produced via factory, but the `RegistryConfig` struct is currently trying to serve the needs of each, which means values that are **required** to be present in the registry section of the config are not used for some concrete registry adapters.

Need to get better with the types here, i.e.

```yaml
  registry:
    type: dev
    fields:
       user: hello
       url: foo.bar.com
```

**Comment by eriknelson** [comment]
There are a finite number of adapter types; k8s uses `Kind`/`Spec` pattern to account for variable schemas, could use:

```
registry:
  kind: dockerhub
  spec:
     key: value
     dockerhub_specific_key: val
```

vs

```
registry:
  kind: otherkind
  spec:
     key: value
     otherkind_specific_key: val
```
