### ISSUE TITLE
Allow clusterwide actions within apb

### ISSUE THREAD

**Issue by karmab** [openshift/ansible-service-broker#576]
**This form is for bug reports and feature requests. Major features will go through a [spec process](https://github.com/openshift/ansible-service-broker/blob/master/CONTRIBUTING.md).**

> # Feature:

as one can be done with say helm, it would be usefull to be able to create namespaces within the apb or define cluster role bindings .

**What happened**:
gets a permission denied 

**What you expected to happen**:
sample code to succeed

**How to reproduce it**:
use the following sample code in an apb 

```
- name: Create crd Role Binding
  k8s_v1beta1_cluster_role_binding:
    name: fission-crd
    role_ref_kind: ClusterRole
    role_ref_name: cluster-admin
    subjects:
    - kind: ServiceAccount
      name: fission-svc
      namespace: "{{ namespace }}"
```
