### ISSUE TITLE
Add ability to specify objects as parameters

### ISSUE THREAD

**Issue by jmrodri** [openshift/ansible-service-broker#851]
**This form is for bug reports and feature requests. Major features will go through a [spec process](https://github.com/openshift/ansible-service-broker/blob/master/CONTRIBUTING.md).**

## Feature: ability to specify objects as parameters

Right now we have a flat parameter list and some folks have wanted to specify objects. We convert our parameters into JSON schema. Would be nice to specify JSON schema (as yaml) in the parameters.

**Comment by jmrodri** [comment]
@rcernich please add any more details about what ran into. Include the original objects you were trying to model, and then some of the ideas you were thinking about.

**Comment by jmrodri** [comment]
Seems related to Issue https://github.com/openshift/ansible-service-broker/issues/347

**Comment by rcernich** [comment]
Object types provide a natural way to organize like parameters.  Arrays would also be useful.  Now take a feature that can be configured multiple times, and each configuration requires multiple settings, you've got an array of objects.

Other than that, the service catalog utilizes json schema directly for the create/update/bind parameters, so exposing that fully would be nice too.

Specific example:
```yaml
_dbConfig: &_dbConfig
  name: dbConfig
  title: Database Configuration
  type: object
  properties:
    DB_USERNAME:
      title: Database Username
      description: Database user name
    DB_PASSWORD:
      title: Database Password
      description: Database user password
    DB_URL:
      title: Database URL
      description: Database name
      default: "postgresql:postgresql-service:5432/root"
    DB_JNDI:
      title: Database JNDI Name
      description: "Database JNDI name used by application to resolve the datasource, e.g. java:/jboss/datasources/postgresql"
      default: "java:jboss/datasources/TodoListDS"
    DB_DRIVER:
      title: Database Driver
      description: Database driver name
      default: postgresql
    DB_MIN_POOL_SIZE:
      title: Datasource Minimum Pool Size
      description: Sets xa-pool/min-pool-size for the configured datasource.
    DB_MAX_POOL_SIZE:
      title: Datasource Maximum Pool Size
      description: Sets xa-pool/max-pool-size for the configured datasource.
    DB_TX_ISOLATION:
      title: Datasource Transaction Isolation
      description: Sets transaction-isolation for the configured datasource.

plans:
  - name: plan1
    parameters:
    - name: datasources
      title: Datasource Definitions
      type: array
      items: *_dbConfig

```
