### ISSUE TITLE
hardcoded path in FileUserServiceAdapter in auth.go 

### ISSUE THREAD

**Issue by jmrodri** [openshift/ansible-service-broker#919]
**This form is for bug reports and feature requests. Major features will go through a [spec process](https://github.com/openshift/ansible-service-broker/blob/master/CONTRIBUTING.md).**

## Bug: 

**What happened**:
Creating an auth secret using a volume path other than `/var/run/asb-auth` will cause the broker to be unable to use basic auth as an authentication mechanism.

**What you expected to happen**:
I should be able to configure a secret and a volume path of my choosing and have the broker use that for basic auth.

**How to reproduce it**:
In the deployment config create a mountPath using `/var/run/sb-auth`.

```yaml
        - image: jmrodri/samplebroker:demo            
          name: samplebroker                          
          imagePullPolicy: IfNotPresent               
          volumeMounts:                               
            - name: config-volume                     
              mountPath: /etc/ansible-service-broker  
            - name: samplebroker-tls                  
              mountPath: /etc/tls/private             
            - name: sb-auth-volume                    
              mountPath: /var/run/sb-auth            
```

In the `volumes` section point the secret to use the above volume
```yaml
        volumes:                                   
        ...
          - name: sb-auth-volume                   
            secret:                                
              secretName: broker-auth-secret       
```
You will see this in the broker logs:
```
[2018-04-27T07:53:33.354Z] [ERROR] - Error reading username. open /var/run/asb-auth/username: no such file or directory
[2018-04-27T07:53:33.354Z] [ERROR] - we had a problem building the DB for FileUserServiceAdapter. %!(EXTRA *os.PathError=open /var/run/asb-auth/username: no such file or directory)
```

Related Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1572521
