### ISSUE TITLE
cannot update optional parameter

### ISSUE THREAD

**Issue by odra** [openshift/ansible-service-broker#934]
## Bug:

**What happened**:

I've created an optional updatable parameter (apb file definition):

```yaml
- name: ANDROID_LICENSE_AGREEMENT
      default: ""
      pattern: ^yes$
      type: string
      description: "Type 'yes' above to accept the Android SDK License Agreement. https://developer.android.com/studio/terms.html"
      title: Android SDK License Agreement
      required: True
      display_group: Android SDK
    - name: ANDROID_SDK_AUTO_CONFIG
      default: 'Yes'
      type: string
      display_type: enum
      enum: ["Yes", "No"]
      description: "Installs the default android sdk packages"
      title: Android SDK Auto Package Install
      required: False
      display_group: Android SDK
    - name: ANDROID_SDK_CONFIG
      default: ""
      type: string
      display_type: textarea
      description: "Android SDK config file content"
      title: Android SDK package config
      required: True
      updatable: True
      display_group: Android SDK
```

I tried using `required: False` but it didn't make a difference.

I get the following error when updating the field:

```
[2018-05-08T13:05:32.152Z] [DEBUG] - Request Params: map[ANDROID_LICENSE_AGREEMENT:yes ANDROID_SDK_AUTO_CONFIG:No ANDROID_SDK_CONFIG:[base]\ntools\nplatform-tools\n\n[platforms]\nandroid-24\nandroid-25\nandroid-26\n\n[build-tools]\n25.0.1\n25.0.3\n\n[extras:google]\ngoogle_play_services\nm2repository\n\n[extras:android]\nm2repository\n\n[keystore]\nalias=AndroidDebugKey\nname=AG\nunit=AeroGear\norg=RedHat\nloc=Waterford\nstate=WD\ncountry=IRL\nstorepass=android\nkeypass=android"]
--
  | [2018-05-08T13:05:32.152Z] [DEBUG] - Previous Params: map[ANDROID_SDK_AUTO_CONFIG:No _apb_plan_id:default _apb_service_class_id:4319a63a322ba4ddcc0d855908ac4f1f _apb_service_instance_id:085d2de7-0b21-4cce-91e5-6cc64adc717b ANDROID_LICENSE_AGREEMENT:yes]
  | [2018-05-08T13:05:32.152Z] [NOTICE] - Requested update parameter: [%!v(MISSING)] with the value of [%!v(MISSING)] was found in an update request, but it did not exist on the previous service instance.
  | [2018-05-08T13:05:32.152Z] [DEBUG] - Changed Params: map[]
  | [2018-05-08T13:05:32.152Z] [DEBUG] - Validated Params: map[]
  | [2018-05-08T13:05:32.152Z] [WARNING] - Returning without running the APB. No changes were actually requested
  | 172.17.0.4 - - [08/May/2018:13:05:32 +0000] "PATCH /ansible-service-broker/v2/service_instances/085d2de7-0b21-4cce-91e5-6cc64adc717b?accepts_incomplete=true HTTP/1.1" 200 3
```

**What you expected to happen**:

That the parameter would be updated  with the new value.

**How to reproduce it**:

Flag a parameter as updatable with the default value set as an empty string and provision the service.

Update the service with the new parameter value after the service has been provisioned.
